import type { Metadata } from "next"
import { Geist } from "next/font/google"
import type { ReactNode } from "react"

import "./globals.css"

import { ThemeProvider } from "next-themes"
import { Providers } from "@/components/providers"
import { cn } from "@/lib/utils"
import Header from "@/components/shadcn-space/blocks/topbar-04/header";
import { TooltipProvider } from "@/components/ui/tooltip"

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("font-sans", geist.variable)}
    >
      <body className="antialiased min-h-svh flex flex-col">
         <TooltipProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>

            {children}
          </Providers>
        </ThemeProvider>
        </TooltipProvider>
      </body>
    </html>
  )
}